---
- name: Fetch MicroK8s join script from master (run once)
  hosts: k8s_masters
  gather_facts: false
  run_once: true
  tasks:
    - name: Ensure join script exists
      ansible.builtin.stat:
        path: /opt/microk8s-join/join-command.sh
      register: join_stat
      become: true

    - name: Read join script
      ansible.builtin.slurp:
        src: /opt/microk8s-join/join-command.sh
      register: join_script
      become: true
      when: join_stat.stat.exists

    - name: Set join script fact for workers
      ansible.builtin.set_fact:
        k8s_join_script: "{{ join_script.content }}"
      when: join_stat.stat.exists

    - name: Show join script (decoded)
      ansible.builtin.debug:
        msg: "{{ (k8s_join_script | b64decode).splitlines() | join('\n') }}"
      when: join_stat.stat.exists

- name: Execute join script on workers
  hosts: k8s_workers
  gather_facts: false
  tasks:
    - name: Fetch join script content from master fact
      ansible.builtin.set_fact:
        join_script_b64: "{{ hostvars[groups['k8s_masters'][0]]['k8s_join_script'] | default('') }}"

    - name: Fail if join script not available
      ansible.builtin.fail:
        msg: "Join script not found on master. Ensure master play ran successfully and /opt/microk8s-join/join-command.sh exists."
      when: join_script_b64 == ''

    - name: Write join script to /tmp/join.sh
      ansible.builtin.copy:
        content: "{{ join_script_b64 | b64decode }}"
        dest: /tmp/join.sh
        mode: "0755"
      become: true

    - name: Run join script
      ansible.builtin.command: /tmp/join.sh
      register: join_run
      become: true
      failed_when: "'error' in join_run.stderr.lower() or join_run.rc not in [0, 1]"
      changed_when: "'joined the cluster' in join_run.stdout"

    - name: Show join result
      ansible.builtin.debug:
        var: join_run

    - name: Check cluster nodes after join (run on worker to query master via kubectl)
      ansible.builtin.command:
        cmd: microk8s kubectl get nodes -o wide
      register: nodes_after_join
      changed_when: false
      become: true
      failed_when: nodes_after_join.rc not in [0]

    - name: Display nodes output
      ansible.builtin.debug:
        msg: "{{ nodes_after_join.stdout | default('no output') }}"
      when: nodes_after_join is defined
