# Example inventory file - copy to hosts.yml and customize
# Converged setup: 3 physical hosts running both K8s and Ceph
all:
  children:
    # Kubernetes cluster nodes
    k8s_masters:
      hosts:
        homelab1:
          ansible_host: homelab1.martinez-saweczko.es
          ansible_user: david
          node_hostname: homelab1

    # Ceph cluster nodes (can overlap with K8s nodes)
    ceph_monitors:
      hosts:
        homelab1:
          ansible_host: 192.168.56.101
          ansible_user: david
          node_hostname: homelab1
        homelab2:
          ansible_host: 192.168.56.102
          ansible_user: david
          node_hostname: homelab2
        homelab3:
          ansible_host: 192.168.56.103
          ansible_user: david
          node_hostname: homelab3

    ceph_osds:
      hosts:
        homelab1:
          ansible_host: homelab1.martinez-saweczko.es
          ansible_user: david
          node_hostname: homelab1
        # node02:
        #   ansible_host: 192.168.1.x
        #   ansible_user: david
        # node03:
        #   ansible_host: 192.168.1.x
        #   ansible_user: david
      vars:
        ceph_osd_devices:
          - /dev/sdb
